# Generated by Django 4.2.3 on 2023-07-15 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic_quest', '0002_remove_category_task_remove_tag_task'),
        ('task', '0006_remove_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='epic_quest.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='epic_quest.tag'),
            preserve_default=False,
        ),
    ]
