# Generated by Django 4.2.3 on 2023-07-15 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic_quest', '0003_alter_category_description'),
        ('task', '0007_task_category_task_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
        migrations.AlterField(
            model_name='task',
            name='status_fields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epic_quest.tag'),
        ),
    ]
