# Generated by Django 4.2.3 on 2023-07-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_quest', '0003_alter_category_description'),
        ('task', '0008_remove_task_tag_alter_task_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(to='epic_quest.tag'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status_fields',
            field=models.CharField(choices=[('start', 'start'), ('done', 'done')], max_length=255),
        ),
    ]
