# Generated by Django 4.2.3 on 2023-07-15 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic_quest', '0006_alter_category_description'),
        ('task', '0009_task_tag_alter_task_status_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='epic_quest.tag'),
            preserve_default=False,
        ),
    ]
