# Generated by Django 4.2.3 on 2023-07-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_quest', '0006_alter_category_description'),
        ('task', '0010_remove_task_tag_task_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(to='epic_quest.tag'),
        ),
    ]
