# Generated by Django 4.2.3 on 2023-07-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_remove_task_tag_task_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_fields',
            field=models.CharField(choices=[('start', 'start'), ('inprocess', 'inprocess'), ('done', 'done')], max_length=255),
        ),
    ]
