# Generated by Django 4.2.4 on 2023-08-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_user_is_greate_user_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_greate_user',
        ),
    ]
