# Generated by Django 4.2.3 on 2023-07-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic_quest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='task',
        ),
    ]
