# Generated by Django 4.2.4 on 2023-08-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic_quest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
