# Generated by Django 4.2.3 on 2023-07-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic_quest', '0006_alter_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
