# Generated by Django 4.2.3 on 2023-07-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.ImageField(default=' ', upload_to='images'),
            preserve_default=False,
        ),
    ]
