# Generated by Django 4.2.3 on 2023-07-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
