# Generated by Django 4.2.4 on 2023-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
